CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL PRIMARY KEY CLUSTERED IDENTITY(1, 1),
	[Guid] UNIQUEIDENTIFIER NOT NULL UNIQUE,
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	UserName NVARCHAR(100) NOT NULL,
)
